name = "metabizlab"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "metabizlab-board"
database_id = "cc39af54-0ed6-48a8-ac4b-347972061ed0"
